docs: Added Java client library document
tigrisdata/tigrisdb-docs pull request #20
Opened 2022-04-13 19:10 UTC by JigarJoshi

2022-04-13 19:23 UTC, himank approved these changes

2022-04-13 19:36 UTC, ovaistariq requested changes

2022-04-13 19:36 UTC, ovaistariq commented on docs/client-libraries/java.md
> +## Client initialization
I suggest breaking these up into its own pages. Take a look at https://www.mongodb.com/docs/drivers/java/sync/current/ as an example

2022-04-13 22:53 UTC, JigarJoshi commented on docs/client-libraries/java.md
> +## Client initialization
Updated documentation, PTAL

2022-04-14 02:17 UTC, ovaistariq approved these changes

2022-04-14 02:17 UTC, merged